#coe_host: "https://127.0.0.1:8443"
#kube_context: "kubernetes-admin@kubernetes"
#config_file: "~/.kube/config"
action: provision
namespace: openstack
service_account: openstack
privileged_service_account: openstack-priv
database_password: weakpassword
cinder_db_password: cinderpass

hieradata: {}
hieradata_file: ''

cinder_config:
  DEFAULT:
    public_bind_host: "0.0.0.0"
  database:
    connection: "mysql+pymysql://root:weakpassword@mariadb:3306/cinder"

enabled_backends: []
